xcopy /s \flags\24x24 \world-countries\src\main\res\mipmap-mdpi
xcopy /s \flags\32x32 \world-countries\src\main\res\mipmap-hdpi
xcopy /s \flags\48x48 \world-countries\src\main\res\mipmap-xhdpi
xcopy /s \flags\64x64 \world-countries\src\main\res\mipmap-xxhdpi
xcopy /s \flags\128x128 \world-countries\src\main\res\mipmap-xxxhdpi
xcopy /s \data\ar\*.json \world-countries\src\main\res\raw-ar
xcopy /s \data\cn\*.json \world-countries\src\main\res\raw-cn
xcopy /s \data\cs\*.json \world-countries\src\main\res\raw-cs
xcopy /s \data\da\*.json \world-countries\src\main\res\raw-da
xcopy /s \data\de\*.json \world-countries\src\main\res\raw-de
xcopy /s \data\el\*.json \world-countries\src\main\res\raw-el
xcopy /s \data\en\*.json \world-countries\src\main\res\raw-en
xcopy /s \data\es\*.json \world-countries\src\main\res\raw-es
xcopy /s \data\et\*.json \world-countries\src\main\res\raw-et
xcopy /s \data\fr\*.json \world-countries\src\main\res\raw-fr
xcopy /s \data\hu\*.json \world-countries\src\main\res\raw-hu
xcopy /s \data\it\*.json \world-countries\src\main\res\raw-it
xcopy /s \data\ja\*.json \world-countries\src\main\res\raw-ja
xcopy /s \data\lt\*.json \world-countries\src\main\res\raw-lt
xcopy /s \data\nl\*.json \world-countries\src\main\res\raw-nl
xcopy /s \data\no\*.json \world-countries\src\main\res\raw-no
xcopy /s \data\pl\*.json \world-countries\src\main\res\raw-pl
xcopy /s \data\pt\*.json \world-countries\src\main\res\raw-pt
xcopy /s \data\ro\*.json \world-countries\src\main\res\raw-ro
xcopy /s \data\ru\*.json \world-countries\src\main\res\raw-ru
xcopy /s \data\sk\*.json \world-countries\src\main\res\raw-sk
xcopy /s \data\th\*.json \world-countries\src\main\res\raw-th
xcopy /s \data\uk\*.json \world-countries\src\main\res\raw-uk