xcopy /s C:\Users\Pozzy\AndroidStudioProjects\world_countries\flags\24x24\    C:\Users\Pozzy\AndroidStudioProjects\world_countries\world-countries\src\main\res\mipmap-mdpi\     /Y
xcopy /s C:\Users\Pozzy\AndroidStudioProjects\world_countries\flags\32x32\    C:\Users\Pozzy\AndroidStudioProjects\world_countries\world-countries\src\main\res\mipmap-hdpi\     /Y
xcopy /s C:\Users\Pozzy\AndroidStudioProjects\world_countries\flags\48x48\    C:\Users\Pozzy\AndroidStudioProjects\world_countries\world-countries\src\main\res\mipmap-xhdpi\    /Y
xcopy /s C:\Users\Pozzy\AndroidStudioProjects\world_countries\flags\64x64\    C:\Users\Pozzy\AndroidStudioProjects\world_countries\world-countries\src\main\res\mipmap-xxhdpi\   /Y
xcopy /s C:\Users\Pozzy\AndroidStudioProjects\world_countries\flags\128x128\  C:\Users\Pozzy\AndroidStudioProjects\world_countries\world-countries\src\main\res\mipmap-xxxhdpi\  /Y
xcopy /s C:\Users\Pozzy\AndroidStudioProjects\world_countries\data\ar\world.csv  C:\Users\Pozzy\AndroidStudioProjects\world_countries\world-countries\src\main\res\raw\ar.csv /Y
xcopy /s C:\Users\Pozzy\AndroidStudioProjects\world_countries\data\cn\world.csv  C:\Users\Pozzy\AndroidStudioProjects\world_countries\world-countries\src\main\res\raw\zh.csv /Y
xcopy /s C:\Users\Pozzy\AndroidStudioProjects\world_countries\data\cs\world.csv  C:\Users\Pozzy\AndroidStudioProjects\world_countries\world-countries\src\main\res\raw\cs.csv /Y
xcopy /s C:\Users\Pozzy\AndroidStudioProjects\world_countries\data\da\world.csv  C:\Users\Pozzy\AndroidStudioProjects\world_countries\world-countries\src\main\res\raw\da.csv /Y
xcopy /s C:\Users\Pozzy\AndroidStudioProjects\world_countries\data\de\world.csv  C:\Users\Pozzy\AndroidStudioProjects\world_countries\world-countries\src\main\res\raw\de.csv /Y
xcopy /s C:\Users\Pozzy\AndroidStudioProjects\world_countries\data\el\world.csv  C:\Users\Pozzy\AndroidStudioProjects\world_countries\world-countries\src\main\res\raw\el.csv /Y
xcopy /s C:\Users\Pozzy\AndroidStudioProjects\world_countries\data\en\world.csv  C:\Users\Pozzy\AndroidStudioProjects\world_countries\world-countries\src\main\res\raw\en.csv /Y
xcopy /s C:\Users\Pozzy\AndroidStudioProjects\world_countries\data\es\world.csv  C:\Users\Pozzy\AndroidStudioProjects\world_countries\world-countries\src\main\res\raw\es.csv /Y
xcopy /s C:\Users\Pozzy\AndroidStudioProjects\world_countries\data\et\world.csv  C:\Users\Pozzy\AndroidStudioProjects\world_countries\world-countries\src\main\res\raw\et.csv /Y
xcopy /s C:\Users\Pozzy\AndroidStudioProjects\world_countries\data\fr\world.csv  C:\Users\Pozzy\AndroidStudioProjects\world_countries\world-countries\src\main\res\raw\fr.csv /Y
xcopy /s C:\Users\Pozzy\AndroidStudioProjects\world_countries\data\hu\world.csv  C:\Users\Pozzy\AndroidStudioProjects\world_countries\world-countries\src\main\res\raw\hu.csv /Y
xcopy /s C:\Users\Pozzy\AndroidStudioProjects\world_countries\data\it\world.csv  C:\Users\Pozzy\AndroidStudioProjects\world_countries\world-countries\src\main\res\raw\it.csv /Y
xcopy /s C:\Users\Pozzy\AndroidStudioProjects\world_countries\data\ja\world.csv  C:\Users\Pozzy\AndroidStudioProjects\world_countries\world-countries\src\main\res\raw\ja.csv /Y
xcopy /s C:\Users\Pozzy\AndroidStudioProjects\world_countries\data\lt\world.csv  C:\Users\Pozzy\AndroidStudioProjects\world_countries\world-countries\src\main\res\raw\lt.csv /Y
xcopy /s C:\Users\Pozzy\AndroidStudioProjects\world_countries\data\nl\world.csv  C:\Users\Pozzy\AndroidStudioProjects\world_countries\world-countries\src\main\res\raw\nl.csv /Y
xcopy /s C:\Users\Pozzy\AndroidStudioProjects\world_countries\data\no\world.csv  C:\Users\Pozzy\AndroidStudioProjects\world_countries\world-countries\src\main\res\raw\no.csv /Y
xcopy /s C:\Users\Pozzy\AndroidStudioProjects\world_countries\data\pl\world.csv  C:\Users\Pozzy\AndroidStudioProjects\world_countries\world-countries\src\main\res\raw\pl.csv /Y
xcopy /s C:\Users\Pozzy\AndroidStudioProjects\world_countries\data\pt\world.csv  C:\Users\Pozzy\AndroidStudioProjects\world_countries\world-countries\src\main\res\raw\pt.csv /Y
xcopy /s C:\Users\Pozzy\AndroidStudioProjects\world_countries\data\ro\world.csv  C:\Users\Pozzy\AndroidStudioProjects\world_countries\world-countries\src\main\res\raw\ro.csv /Y
xcopy /s C:\Users\Pozzy\AndroidStudioProjects\world_countries\data\ru\world.csv  C:\Users\Pozzy\AndroidStudioProjects\world_countries\world-countries\src\main\res\raw\ru.csv /Y
xcopy /s C:\Users\Pozzy\AndroidStudioProjects\world_countries\data\sk\world.csv  C:\Users\Pozzy\AndroidStudioProjects\world_countries\world-countries\src\main\res\raw\sk.csv /Y
xcopy /s C:\Users\Pozzy\AndroidStudioProjects\world_countries\data\th\world.csv  C:\Users\Pozzy\AndroidStudioProjects\world_countries\world-countries\src\main\res\raw\th.csv /Y
xcopy /s C:\Users\Pozzy\AndroidStudioProjects\world_countries\data\uk\world.csv  C:\Users\Pozzy\AndroidStudioProjects\world_countries\world-countries\src\main\res\raw\uk.csv /Y